[package]
name = "wei-run"
version = "0.1.8"
edition = "2021"
description = "wei run"
documentation = "https://github.com/zuiyue-com/wei-run"
homepage = "https://github.com/zuiyue-com/wei-run"
license = "MIT OR Apache-2.0"

[dependencies]
# encoding_rs = "0.8.32"
wei-env = "0.2.4"
winapi = { version = "0.3", features = ["winbase"] }
